<!--
<html>
    <head></head>

    <body>
        <h1>Olakunle</h1>
        <form method="post" action="/loan">
            Name: <input type="text" name="name" placeholder="Fullname" /> <br>
            Personal Identification Number: <input type="text" name="pin" placeholder="PIN" /> <br>
            Loan Amount: <input type="text" name="loan_amt" placeholder="Amount" /> <br>
            Period: <input type="text" name="duration" placeholder="In months" /> <br>
            Purpose: <textarea name="purpose" cols="80" rows="10" placeholder="Purpose"></textarea><br>
            <button>Submit</button>
        </form>
    </body>
</html>
-->

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Loan</title>
  </head>
  <body class="bg-light">
    <!--<h1>Loan Application</h1>-->

    <div class="container" style="width:500px;">
     <h4 align="">Loan Application</h4>
        <label class='text-success'><?= $options['success'] ?></label><br />
        <label class='text-danger'><?= $options['error'] ?></label><br />

        <?php foreach($options['validation_messages'] as $msg) : ?>
          <label class='text-danger'><?= $msg ?></label><br/>
        <?php endforeach; ?>

        <form method="post" action="/loan">
            <label>Name</label>
            <input type="text" name="name" class="form-control" required/><br />
            <label>Personal Identification Number</label>
            <input type="text" name="pin" class="form-control" required /><br />
            <label>Loan Amount</label>
            <input type="number" name="loan_amt" class="form-control" required/><br />
            <label>Period</label>
            <input type="number" name="period" placeholder="in Months" class="form-control" required/><br />
            <label>Purpose</label>
            <textarea class="form-control" name="purpose" rows="3" required></textarea>
            <br />
            <input type="submit" name="submit" value="Apply" class="btn btn-info" /><br />
        </form>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>
